"""initial_schema

Revision ID: 80c920ba0eb4
Revises:
Create Date: 2026-06-11 13:28:44.572621

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '80c920ba0eb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('input_filename', sa.String(length=512), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=False),
    sa.Column('output_format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('output_pdf_path', sa.String(length=1024), nullable=True),
    sa.Column('output_tex_path', sa.String(length=1024), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=256), nullable=True),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('monthly_usage', sa.Integer(), nullable=False),
    sa.Column('last_reset_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('jobs')
    # ### end Alembic commands ###
